#pragma once

#include "SensorDigital.h"

template <typename T, unsigned char SENSOR_NUMBER>
class SensorMatch { 
  private:
    T &m_sensor;
    bool m_lastRead[SENSOR_NUMBER];   
  public:
    constexpr static char PATTERN_BLACK = 'B';
    constexpr static char PATTERN_WHITE = 'W';
    constexpr static char PATTERN_ANY   = '?';
    SensorMatch(T &sensor): m_sensor(sensor){}

    inline void update() {
      for (char i = 0; i < SENSOR_NUMBER; i ++){
        m_lastRead[i] = m_sensor.readSensor(i);
      }
    }
    inline bool isBlack(uint8_t n){
      return m_lastRead[n];  
    }
};

#define M_B(sensor, n) ((sensor)->isBlack(n))
#define M_W(sensor, n) (!(sensor)->isBlack(n))
#define M_A(sensor, n) (1)

#define MATCH_WWWWW(sensor) (M_W(sensor, 0)&&M_W(sensor, 1)&&M_W(sensor, 2)&&M_W(sensor, 3)&&M_W(sensor, 4))
#define MATCH_BWWWW(sensor) (M_B(sensor, 0)&&M_W(sensor, 1)&&M_W(sensor, 2)&&M_W(sensor, 3)&&M_W(sensor, 4))
#define MATCH_AWWWW(sensor) (M_A(sensor, 0)&&M_W(sensor, 1)&&M_W(sensor, 2)&&M_W(sensor, 3)&&M_W(sensor, 4))
#define MATCH_WBWWW(sensor) (M_W(sensor, 0)&&M_B(sensor, 1)&&M_W(sensor, 2)&&M_W(sensor, 3)&&M_W(sensor, 4))
#define MATCH_BBWWW(sensor) (M_B(sensor, 0)&&M_B(sensor, 1)&&M_W(sensor, 2)&&M_W(sensor, 3)&&M_W(sensor, 4))
#define MATCH_ABWWW(sensor) (M_A(sensor, 0)&&M_B(sensor, 1)&&M_W(sensor, 2)&&M_W(sensor, 3)&&M_W(sensor, 4))
#define MATCH_WAWWW(sensor) (M_W(sensor, 0)&&M_A(sensor, 1)&&M_W(sensor, 2)&&M_W(sensor, 3)&&M_W(sensor, 4))
#define MATCH_BAWWW(sensor) (M_B(sensor, 0)&&M_A(sensor, 1)&&M_W(sensor, 2)&&M_W(sensor, 3)&&M_W(sensor, 4))
#define MATCH_AAWWW(sensor) (M_A(sensor, 0)&&M_A(sensor, 1)&&M_W(sensor, 2)&&M_W(sensor, 3)&&M_W(sensor, 4))
#define MATCH_WWBWW(sensor) (M_W(sensor, 0)&&M_W(sensor, 1)&&M_B(sensor, 2)&&M_W(sensor, 3)&&M_W(sensor, 4))
#define MATCH_BWBWW(sensor) (M_B(sensor, 0)&&M_W(sensor, 1)&&M_B(sensor, 2)&&M_W(sensor, 3)&&M_W(sensor, 4))
#define MATCH_AWBWW(sensor) (M_A(sensor, 0)&&M_W(sensor, 1)&&M_B(sensor, 2)&&M_W(sensor, 3)&&M_W(sensor, 4))
#define MATCH_WBBWW(sensor) (M_W(sensor, 0)&&M_B(sensor, 1)&&M_B(sensor, 2)&&M_W(sensor, 3)&&M_W(sensor, 4))
#define MATCH_BBBWW(sensor) (M_B(sensor, 0)&&M_B(sensor, 1)&&M_B(sensor, 2)&&M_W(sensor, 3)&&M_W(sensor, 4))
#define MATCH_ABBWW(sensor) (M_A(sensor, 0)&&M_B(sensor, 1)&&M_B(sensor, 2)&&M_W(sensor, 3)&&M_W(sensor, 4))
#define MATCH_WABWW(sensor) (M_W(sensor, 0)&&M_A(sensor, 1)&&M_B(sensor, 2)&&M_W(sensor, 3)&&M_W(sensor, 4))
#define MATCH_BABWW(sensor) (M_B(sensor, 0)&&M_A(sensor, 1)&&M_B(sensor, 2)&&M_W(sensor, 3)&&M_W(sensor, 4))
#define MATCH_AABWW(sensor) (M_A(sensor, 0)&&M_A(sensor, 1)&&M_B(sensor, 2)&&M_W(sensor, 3)&&M_W(sensor, 4))
#define MATCH_WWAWW(sensor) (M_W(sensor, 0)&&M_W(sensor, 1)&&M_A(sensor, 2)&&M_W(sensor, 3)&&M_W(sensor, 4))
#define MATCH_BWAWW(sensor) (M_B(sensor, 0)&&M_W(sensor, 1)&&M_A(sensor, 2)&&M_W(sensor, 3)&&M_W(sensor, 4))
#define MATCH_AWAWW(sensor) (M_A(sensor, 0)&&M_W(sensor, 1)&&M_A(sensor, 2)&&M_W(sensor, 3)&&M_W(sensor, 4))
#define MATCH_WBAWW(sensor) (M_W(sensor, 0)&&M_B(sensor, 1)&&M_A(sensor, 2)&&M_W(sensor, 3)&&M_W(sensor, 4))
#define MATCH_BBAWW(sensor) (M_B(sensor, 0)&&M_B(sensor, 1)&&M_A(sensor, 2)&&M_W(sensor, 3)&&M_W(sensor, 4))
#define MATCH_ABAWW(sensor) (M_A(sensor, 0)&&M_B(sensor, 1)&&M_A(sensor, 2)&&M_W(sensor, 3)&&M_W(sensor, 4))
#define MATCH_WAAWW(sensor) (M_W(sensor, 0)&&M_A(sensor, 1)&&M_A(sensor, 2)&&M_W(sensor, 3)&&M_W(sensor, 4))
#define MATCH_BAAWW(sensor) (M_B(sensor, 0)&&M_A(sensor, 1)&&M_A(sensor, 2)&&M_W(sensor, 3)&&M_W(sensor, 4))
#define MATCH_AAAWW(sensor) (M_A(sensor, 0)&&M_A(sensor, 1)&&M_A(sensor, 2)&&M_W(sensor, 3)&&M_W(sensor, 4))
#define MATCH_WWWBW(sensor) (M_W(sensor, 0)&&M_W(sensor, 1)&&M_W(sensor, 2)&&M_B(sensor, 3)&&M_W(sensor, 4))
#define MATCH_BWWBW(sensor) (M_B(sensor, 0)&&M_W(sensor, 1)&&M_W(sensor, 2)&&M_B(sensor, 3)&&M_W(sensor, 4))
#define MATCH_AWWBW(sensor) (M_A(sensor, 0)&&M_W(sensor, 1)&&M_W(sensor, 2)&&M_B(sensor, 3)&&M_W(sensor, 4))
#define MATCH_WBWBW(sensor) (M_W(sensor, 0)&&M_B(sensor, 1)&&M_W(sensor, 2)&&M_B(sensor, 3)&&M_W(sensor, 4))
#define MATCH_BBWBW(sensor) (M_B(sensor, 0)&&M_B(sensor, 1)&&M_W(sensor, 2)&&M_B(sensor, 3)&&M_W(sensor, 4))
#define MATCH_ABWBW(sensor) (M_A(sensor, 0)&&M_B(sensor, 1)&&M_W(sensor, 2)&&M_B(sensor, 3)&&M_W(sensor, 4))
#define MATCH_WAWBW(sensor) (M_W(sensor, 0)&&M_A(sensor, 1)&&M_W(sensor, 2)&&M_B(sensor, 3)&&M_W(sensor, 4))
#define MATCH_BAWBW(sensor) (M_B(sensor, 0)&&M_A(sensor, 1)&&M_W(sensor, 2)&&M_B(sensor, 3)&&M_W(sensor, 4))
#define MATCH_AAWBW(sensor) (M_A(sensor, 0)&&M_A(sensor, 1)&&M_W(sensor, 2)&&M_B(sensor, 3)&&M_W(sensor, 4))
#define MATCH_WWBBW(sensor) (M_W(sensor, 0)&&M_W(sensor, 1)&&M_B(sensor, 2)&&M_B(sensor, 3)&&M_W(sensor, 4))
#define MATCH_BWBBW(sensor) (M_B(sensor, 0)&&M_W(sensor, 1)&&M_B(sensor, 2)&&M_B(sensor, 3)&&M_W(sensor, 4))
#define MATCH_AWBBW(sensor) (M_A(sensor, 0)&&M_W(sensor, 1)&&M_B(sensor, 2)&&M_B(sensor, 3)&&M_W(sensor, 4))
#define MATCH_WBBBW(sensor) (M_W(sensor, 0)&&M_B(sensor, 1)&&M_B(sensor, 2)&&M_B(sensor, 3)&&M_W(sensor, 4))
#define MATCH_BBBBW(sensor) (M_B(sensor, 0)&&M_B(sensor, 1)&&M_B(sensor, 2)&&M_B(sensor, 3)&&M_W(sensor, 4))
#define MATCH_ABBBW(sensor) (M_A(sensor, 0)&&M_B(sensor, 1)&&M_B(sensor, 2)&&M_B(sensor, 3)&&M_W(sensor, 4))
#define MATCH_WABBW(sensor) (M_W(sensor, 0)&&M_A(sensor, 1)&&M_B(sensor, 2)&&M_B(sensor, 3)&&M_W(sensor, 4))
#define MATCH_BABBW(sensor) (M_B(sensor, 0)&&M_A(sensor, 1)&&M_B(sensor, 2)&&M_B(sensor, 3)&&M_W(sensor, 4))
#define MATCH_AABBW(sensor) (M_A(sensor, 0)&&M_A(sensor, 1)&&M_B(sensor, 2)&&M_B(sensor, 3)&&M_W(sensor, 4))
#define MATCH_WWABW(sensor) (M_W(sensor, 0)&&M_W(sensor, 1)&&M_A(sensor, 2)&&M_B(sensor, 3)&&M_W(sensor, 4))
#define MATCH_BWABW(sensor) (M_B(sensor, 0)&&M_W(sensor, 1)&&M_A(sensor, 2)&&M_B(sensor, 3)&&M_W(sensor, 4))
#define MATCH_AWABW(sensor) (M_A(sensor, 0)&&M_W(sensor, 1)&&M_A(sensor, 2)&&M_B(sensor, 3)&&M_W(sensor, 4))
#define MATCH_WBABW(sensor) (M_W(sensor, 0)&&M_B(sensor, 1)&&M_A(sensor, 2)&&M_B(sensor, 3)&&M_W(sensor, 4))
#define MATCH_BBABW(sensor) (M_B(sensor, 0)&&M_B(sensor, 1)&&M_A(sensor, 2)&&M_B(sensor, 3)&&M_W(sensor, 4))
#define MATCH_ABABW(sensor) (M_A(sensor, 0)&&M_B(sensor, 1)&&M_A(sensor, 2)&&M_B(sensor, 3)&&M_W(sensor, 4))
#define MATCH_WAABW(sensor) (M_W(sensor, 0)&&M_A(sensor, 1)&&M_A(sensor, 2)&&M_B(sensor, 3)&&M_W(sensor, 4))
#define MATCH_BAABW(sensor) (M_B(sensor, 0)&&M_A(sensor, 1)&&M_A(sensor, 2)&&M_B(sensor, 3)&&M_W(sensor, 4))
#define MATCH_AAABW(sensor) (M_A(sensor, 0)&&M_A(sensor, 1)&&M_A(sensor, 2)&&M_B(sensor, 3)&&M_W(sensor, 4))
#define MATCH_WWWAW(sensor) (M_W(sensor, 0)&&M_W(sensor, 1)&&M_W(sensor, 2)&&M_A(sensor, 3)&&M_W(sensor, 4))
#define MATCH_BWWAW(sensor) (M_B(sensor, 0)&&M_W(sensor, 1)&&M_W(sensor, 2)&&M_A(sensor, 3)&&M_W(sensor, 4))
#define MATCH_AWWAW(sensor) (M_A(sensor, 0)&&M_W(sensor, 1)&&M_W(sensor, 2)&&M_A(sensor, 3)&&M_W(sensor, 4))
#define MATCH_WBWAW(sensor) (M_W(sensor, 0)&&M_B(sensor, 1)&&M_W(sensor, 2)&&M_A(sensor, 3)&&M_W(sensor, 4))
#define MATCH_BBWAW(sensor) (M_B(sensor, 0)&&M_B(sensor, 1)&&M_W(sensor, 2)&&M_A(sensor, 3)&&M_W(sensor, 4))
#define MATCH_ABWAW(sensor) (M_A(sensor, 0)&&M_B(sensor, 1)&&M_W(sensor, 2)&&M_A(sensor, 3)&&M_W(sensor, 4))
#define MATCH_WAWAW(sensor) (M_W(sensor, 0)&&M_A(sensor, 1)&&M_W(sensor, 2)&&M_A(sensor, 3)&&M_W(sensor, 4))
#define MATCH_BAWAW(sensor) (M_B(sensor, 0)&&M_A(sensor, 1)&&M_W(sensor, 2)&&M_A(sensor, 3)&&M_W(sensor, 4))
#define MATCH_AAWAW(sensor) (M_A(sensor, 0)&&M_A(sensor, 1)&&M_W(sensor, 2)&&M_A(sensor, 3)&&M_W(sensor, 4))
#define MATCH_WWBAW(sensor) (M_W(sensor, 0)&&M_W(sensor, 1)&&M_B(sensor, 2)&&M_A(sensor, 3)&&M_W(sensor, 4))
#define MATCH_BWBAW(sensor) (M_B(sensor, 0)&&M_W(sensor, 1)&&M_B(sensor, 2)&&M_A(sensor, 3)&&M_W(sensor, 4))
#define MATCH_AWBAW(sensor) (M_A(sensor, 0)&&M_W(sensor, 1)&&M_B(sensor, 2)&&M_A(sensor, 3)&&M_W(sensor, 4))
#define MATCH_WBBAW(sensor) (M_W(sensor, 0)&&M_B(sensor, 1)&&M_B(sensor, 2)&&M_A(sensor, 3)&&M_W(sensor, 4))
#define MATCH_BBBAW(sensor) (M_B(sensor, 0)&&M_B(sensor, 1)&&M_B(sensor, 2)&&M_A(sensor, 3)&&M_W(sensor, 4))
#define MATCH_ABBAW(sensor) (M_A(sensor, 0)&&M_B(sensor, 1)&&M_B(sensor, 2)&&M_A(sensor, 3)&&M_W(sensor, 4))
#define MATCH_WABAW(sensor) (M_W(sensor, 0)&&M_A(sensor, 1)&&M_B(sensor, 2)&&M_A(sensor, 3)&&M_W(sensor, 4))
#define MATCH_BABAW(sensor) (M_B(sensor, 0)&&M_A(sensor, 1)&&M_B(sensor, 2)&&M_A(sensor, 3)&&M_W(sensor, 4))
#define MATCH_AABAW(sensor) (M_A(sensor, 0)&&M_A(sensor, 1)&&M_B(sensor, 2)&&M_A(sensor, 3)&&M_W(sensor, 4))
#define MATCH_WWAAW(sensor) (M_W(sensor, 0)&&M_W(sensor, 1)&&M_A(sensor, 2)&&M_A(sensor, 3)&&M_W(sensor, 4))
#define MATCH_BWAAW(sensor) (M_B(sensor, 0)&&M_W(sensor, 1)&&M_A(sensor, 2)&&M_A(sensor, 3)&&M_W(sensor, 4))
#define MATCH_AWAAW(sensor) (M_A(sensor, 0)&&M_W(sensor, 1)&&M_A(sensor, 2)&&M_A(sensor, 3)&&M_W(sensor, 4))
#define MATCH_WBAAW(sensor) (M_W(sensor, 0)&&M_B(sensor, 1)&&M_A(sensor, 2)&&M_A(sensor, 3)&&M_W(sensor, 4))
#define MATCH_BBAAW(sensor) (M_B(sensor, 0)&&M_B(sensor, 1)&&M_A(sensor, 2)&&M_A(sensor, 3)&&M_W(sensor, 4))
#define MATCH_ABAAW(sensor) (M_A(sensor, 0)&&M_B(sensor, 1)&&M_A(sensor, 2)&&M_A(sensor, 3)&&M_W(sensor, 4))
#define MATCH_WAAAW(sensor) (M_W(sensor, 0)&&M_A(sensor, 1)&&M_A(sensor, 2)&&M_A(sensor, 3)&&M_W(sensor, 4))
#define MATCH_BAAAW(sensor) (M_B(sensor, 0)&&M_A(sensor, 1)&&M_A(sensor, 2)&&M_A(sensor, 3)&&M_W(sensor, 4))
#define MATCH_AAAAW(sensor) (M_A(sensor, 0)&&M_A(sensor, 1)&&M_A(sensor, 2)&&M_A(sensor, 3)&&M_W(sensor, 4))
#define MATCH_WWWWB(sensor) (M_W(sensor, 0)&&M_W(sensor, 1)&&M_W(sensor, 2)&&M_W(sensor, 3)&&M_B(sensor, 4))
#define MATCH_BWWWB(sensor) (M_B(sensor, 0)&&M_W(sensor, 1)&&M_W(sensor, 2)&&M_W(sensor, 3)&&M_B(sensor, 4))
#define MATCH_AWWWB(sensor) (M_A(sensor, 0)&&M_W(sensor, 1)&&M_W(sensor, 2)&&M_W(sensor, 3)&&M_B(sensor, 4))
#define MATCH_WBWWB(sensor) (M_W(sensor, 0)&&M_B(sensor, 1)&&M_W(sensor, 2)&&M_W(sensor, 3)&&M_B(sensor, 4))
#define MATCH_BBWWB(sensor) (M_B(sensor, 0)&&M_B(sensor, 1)&&M_W(sensor, 2)&&M_W(sensor, 3)&&M_B(sensor, 4))
#define MATCH_ABWWB(sensor) (M_A(sensor, 0)&&M_B(sensor, 1)&&M_W(sensor, 2)&&M_W(sensor, 3)&&M_B(sensor, 4))
#define MATCH_WAWWB(sensor) (M_W(sensor, 0)&&M_A(sensor, 1)&&M_W(sensor, 2)&&M_W(sensor, 3)&&M_B(sensor, 4))
#define MATCH_BAWWB(sensor) (M_B(sensor, 0)&&M_A(sensor, 1)&&M_W(sensor, 2)&&M_W(sensor, 3)&&M_B(sensor, 4))
#define MATCH_AAWWB(sensor) (M_A(sensor, 0)&&M_A(sensor, 1)&&M_W(sensor, 2)&&M_W(sensor, 3)&&M_B(sensor, 4))
#define MATCH_WWBWB(sensor) (M_W(sensor, 0)&&M_W(sensor, 1)&&M_B(sensor, 2)&&M_W(sensor, 3)&&M_B(sensor, 4))
#define MATCH_BWBWB(sensor) (M_B(sensor, 0)&&M_W(sensor, 1)&&M_B(sensor, 2)&&M_W(sensor, 3)&&M_B(sensor, 4))
#define MATCH_AWBWB(sensor) (M_A(sensor, 0)&&M_W(sensor, 1)&&M_B(sensor, 2)&&M_W(sensor, 3)&&M_B(sensor, 4))
#define MATCH_WBBWB(sensor) (M_W(sensor, 0)&&M_B(sensor, 1)&&M_B(sensor, 2)&&M_W(sensor, 3)&&M_B(sensor, 4))
#define MATCH_BBBWB(sensor) (M_B(sensor, 0)&&M_B(sensor, 1)&&M_B(sensor, 2)&&M_W(sensor, 3)&&M_B(sensor, 4))
#define MATCH_ABBWB(sensor) (M_A(sensor, 0)&&M_B(sensor, 1)&&M_B(sensor, 2)&&M_W(sensor, 3)&&M_B(sensor, 4))
#define MATCH_WABWB(sensor) (M_W(sensor, 0)&&M_A(sensor, 1)&&M_B(sensor, 2)&&M_W(sensor, 3)&&M_B(sensor, 4))
#define MATCH_BABWB(sensor) (M_B(sensor, 0)&&M_A(sensor, 1)&&M_B(sensor, 2)&&M_W(sensor, 3)&&M_B(sensor, 4))
#define MATCH_AABWB(sensor) (M_A(sensor, 0)&&M_A(sensor, 1)&&M_B(sensor, 2)&&M_W(sensor, 3)&&M_B(sensor, 4))
#define MATCH_WWAWB(sensor) (M_W(sensor, 0)&&M_W(sensor, 1)&&M_A(sensor, 2)&&M_W(sensor, 3)&&M_B(sensor, 4))
#define MATCH_BWAWB(sensor) (M_B(sensor, 0)&&M_W(sensor, 1)&&M_A(sensor, 2)&&M_W(sensor, 3)&&M_B(sensor, 4))
#define MATCH_AWAWB(sensor) (M_A(sensor, 0)&&M_W(sensor, 1)&&M_A(sensor, 2)&&M_W(sensor, 3)&&M_B(sensor, 4))
#define MATCH_WBAWB(sensor) (M_W(sensor, 0)&&M_B(sensor, 1)&&M_A(sensor, 2)&&M_W(sensor, 3)&&M_B(sensor, 4))
#define MATCH_BBAWB(sensor) (M_B(sensor, 0)&&M_B(sensor, 1)&&M_A(sensor, 2)&&M_W(sensor, 3)&&M_B(sensor, 4))
#define MATCH_ABAWB(sensor) (M_A(sensor, 0)&&M_B(sensor, 1)&&M_A(sensor, 2)&&M_W(sensor, 3)&&M_B(sensor, 4))
#define MATCH_WAAWB(sensor) (M_W(sensor, 0)&&M_A(sensor, 1)&&M_A(sensor, 2)&&M_W(sensor, 3)&&M_B(sensor, 4))
#define MATCH_BAAWB(sensor) (M_B(sensor, 0)&&M_A(sensor, 1)&&M_A(sensor, 2)&&M_W(sensor, 3)&&M_B(sensor, 4))
#define MATCH_AAAWB(sensor) (M_A(sensor, 0)&&M_A(sensor, 1)&&M_A(sensor, 2)&&M_W(sensor, 3)&&M_B(sensor, 4))
#define MATCH_WWWBB(sensor) (M_W(sensor, 0)&&M_W(sensor, 1)&&M_W(sensor, 2)&&M_B(sensor, 3)&&M_B(sensor, 4))
#define MATCH_BWWBB(sensor) (M_B(sensor, 0)&&M_W(sensor, 1)&&M_W(sensor, 2)&&M_B(sensor, 3)&&M_B(sensor, 4))
#define MATCH_AWWBB(sensor) (M_A(sensor, 0)&&M_W(sensor, 1)&&M_W(sensor, 2)&&M_B(sensor, 3)&&M_B(sensor, 4))
#define MATCH_WBWBB(sensor) (M_W(sensor, 0)&&M_B(sensor, 1)&&M_W(sensor, 2)&&M_B(sensor, 3)&&M_B(sensor, 4))
#define MATCH_BBWBB(sensor) (M_B(sensor, 0)&&M_B(sensor, 1)&&M_W(sensor, 2)&&M_B(sensor, 3)&&M_B(sensor, 4))
#define MATCH_ABWBB(sensor) (M_A(sensor, 0)&&M_B(sensor, 1)&&M_W(sensor, 2)&&M_B(sensor, 3)&&M_B(sensor, 4))
#define MATCH_WAWBB(sensor) (M_W(sensor, 0)&&M_A(sensor, 1)&&M_W(sensor, 2)&&M_B(sensor, 3)&&M_B(sensor, 4))
#define MATCH_BAWBB(sensor) (M_B(sensor, 0)&&M_A(sensor, 1)&&M_W(sensor, 2)&&M_B(sensor, 3)&&M_B(sensor, 4))
#define MATCH_AAWBB(sensor) (M_A(sensor, 0)&&M_A(sensor, 1)&&M_W(sensor, 2)&&M_B(sensor, 3)&&M_B(sensor, 4))
#define MATCH_WWBBB(sensor) (M_W(sensor, 0)&&M_W(sensor, 1)&&M_B(sensor, 2)&&M_B(sensor, 3)&&M_B(sensor, 4))
#define MATCH_BWBBB(sensor) (M_B(sensor, 0)&&M_W(sensor, 1)&&M_B(sensor, 2)&&M_B(sensor, 3)&&M_B(sensor, 4))
#define MATCH_AWBBB(sensor) (M_A(sensor, 0)&&M_W(sensor, 1)&&M_B(sensor, 2)&&M_B(sensor, 3)&&M_B(sensor, 4))
#define MATCH_WBBBB(sensor) (M_W(sensor, 0)&&M_B(sensor, 1)&&M_B(sensor, 2)&&M_B(sensor, 3)&&M_B(sensor, 4))
#define MATCH_BBBBB(sensor) (M_B(sensor, 0)&&M_B(sensor, 1)&&M_B(sensor, 2)&&M_B(sensor, 3)&&M_B(sensor, 4))
#define MATCH_ABBBB(sensor) (M_A(sensor, 0)&&M_B(sensor, 1)&&M_B(sensor, 2)&&M_B(sensor, 3)&&M_B(sensor, 4))
#define MATCH_WABBB(sensor) (M_W(sensor, 0)&&M_A(sensor, 1)&&M_B(sensor, 2)&&M_B(sensor, 3)&&M_B(sensor, 4))
#define MATCH_BABBB(sensor) (M_B(sensor, 0)&&M_A(sensor, 1)&&M_B(sensor, 2)&&M_B(sensor, 3)&&M_B(sensor, 4))
#define MATCH_AABBB(sensor) (M_A(sensor, 0)&&M_A(sensor, 1)&&M_B(sensor, 2)&&M_B(sensor, 3)&&M_B(sensor, 4))
#define MATCH_WWABB(sensor) (M_W(sensor, 0)&&M_W(sensor, 1)&&M_A(sensor, 2)&&M_B(sensor, 3)&&M_B(sensor, 4))
#define MATCH_BWABB(sensor) (M_B(sensor, 0)&&M_W(sensor, 1)&&M_A(sensor, 2)&&M_B(sensor, 3)&&M_B(sensor, 4))
#define MATCH_AWABB(sensor) (M_A(sensor, 0)&&M_W(sensor, 1)&&M_A(sensor, 2)&&M_B(sensor, 3)&&M_B(sensor, 4))
#define MATCH_WBABB(sensor) (M_W(sensor, 0)&&M_B(sensor, 1)&&M_A(sensor, 2)&&M_B(sensor, 3)&&M_B(sensor, 4))
#define MATCH_BBABB(sensor) (M_B(sensor, 0)&&M_B(sensor, 1)&&M_A(sensor, 2)&&M_B(sensor, 3)&&M_B(sensor, 4))
#define MATCH_ABABB(sensor) (M_A(sensor, 0)&&M_B(sensor, 1)&&M_A(sensor, 2)&&M_B(sensor, 3)&&M_B(sensor, 4))
#define MATCH_WAABB(sensor) (M_W(sensor, 0)&&M_A(sensor, 1)&&M_A(sensor, 2)&&M_B(sensor, 3)&&M_B(sensor, 4))
#define MATCH_BAABB(sensor) (M_B(sensor, 0)&&M_A(sensor, 1)&&M_A(sensor, 2)&&M_B(sensor, 3)&&M_B(sensor, 4))
#define MATCH_AAABB(sensor) (M_A(sensor, 0)&&M_A(sensor, 1)&&M_A(sensor, 2)&&M_B(sensor, 3)&&M_B(sensor, 4))
#define MATCH_WWWAB(sensor) (M_W(sensor, 0)&&M_W(sensor, 1)&&M_W(sensor, 2)&&M_A(sensor, 3)&&M_B(sensor, 4))
#define MATCH_BWWAB(sensor) (M_B(sensor, 0)&&M_W(sensor, 1)&&M_W(sensor, 2)&&M_A(sensor, 3)&&M_B(sensor, 4))
#define MATCH_AWWAB(sensor) (M_A(sensor, 0)&&M_W(sensor, 1)&&M_W(sensor, 2)&&M_A(sensor, 3)&&M_B(sensor, 4))
#define MATCH_WBWAB(sensor) (M_W(sensor, 0)&&M_B(sensor, 1)&&M_W(sensor, 2)&&M_A(sensor, 3)&&M_B(sensor, 4))
#define MATCH_BBWAB(sensor) (M_B(sensor, 0)&&M_B(sensor, 1)&&M_W(sensor, 2)&&M_A(sensor, 3)&&M_B(sensor, 4))
#define MATCH_ABWAB(sensor) (M_A(sensor, 0)&&M_B(sensor, 1)&&M_W(sensor, 2)&&M_A(sensor, 3)&&M_B(sensor, 4))
#define MATCH_WAWAB(sensor) (M_W(sensor, 0)&&M_A(sensor, 1)&&M_W(sensor, 2)&&M_A(sensor, 3)&&M_B(sensor, 4))
#define MATCH_BAWAB(sensor) (M_B(sensor, 0)&&M_A(sensor, 1)&&M_W(sensor, 2)&&M_A(sensor, 3)&&M_B(sensor, 4))
#define MATCH_AAWAB(sensor) (M_A(sensor, 0)&&M_A(sensor, 1)&&M_W(sensor, 2)&&M_A(sensor, 3)&&M_B(sensor, 4))
#define MATCH_WWBAB(sensor) (M_W(sensor, 0)&&M_W(sensor, 1)&&M_B(sensor, 2)&&M_A(sensor, 3)&&M_B(sensor, 4))
#define MATCH_BWBAB(sensor) (M_B(sensor, 0)&&M_W(sensor, 1)&&M_B(sensor, 2)&&M_A(sensor, 3)&&M_B(sensor, 4))
#define MATCH_AWBAB(sensor) (M_A(sensor, 0)&&M_W(sensor, 1)&&M_B(sensor, 2)&&M_A(sensor, 3)&&M_B(sensor, 4))
#define MATCH_WBBAB(sensor) (M_W(sensor, 0)&&M_B(sensor, 1)&&M_B(sensor, 2)&&M_A(sensor, 3)&&M_B(sensor, 4))
#define MATCH_BBBAB(sensor) (M_B(sensor, 0)&&M_B(sensor, 1)&&M_B(sensor, 2)&&M_A(sensor, 3)&&M_B(sensor, 4))
#define MATCH_ABBAB(sensor) (M_A(sensor, 0)&&M_B(sensor, 1)&&M_B(sensor, 2)&&M_A(sensor, 3)&&M_B(sensor, 4))
#define MATCH_WABAB(sensor) (M_W(sensor, 0)&&M_A(sensor, 1)&&M_B(sensor, 2)&&M_A(sensor, 3)&&M_B(sensor, 4))
#define MATCH_BABAB(sensor) (M_B(sensor, 0)&&M_A(sensor, 1)&&M_B(sensor, 2)&&M_A(sensor, 3)&&M_B(sensor, 4))
#define MATCH_AABAB(sensor) (M_A(sensor, 0)&&M_A(sensor, 1)&&M_B(sensor, 2)&&M_A(sensor, 3)&&M_B(sensor, 4))
#define MATCH_WWAAB(sensor) (M_W(sensor, 0)&&M_W(sensor, 1)&&M_A(sensor, 2)&&M_A(sensor, 3)&&M_B(sensor, 4))
#define MATCH_BWAAB(sensor) (M_B(sensor, 0)&&M_W(sensor, 1)&&M_A(sensor, 2)&&M_A(sensor, 3)&&M_B(sensor, 4))
#define MATCH_AWAAB(sensor) (M_A(sensor, 0)&&M_W(sensor, 1)&&M_A(sensor, 2)&&M_A(sensor, 3)&&M_B(sensor, 4))
#define MATCH_WBAAB(sensor) (M_W(sensor, 0)&&M_B(sensor, 1)&&M_A(sensor, 2)&&M_A(sensor, 3)&&M_B(sensor, 4))
#define MATCH_BBAAB(sensor) (M_B(sensor, 0)&&M_B(sensor, 1)&&M_A(sensor, 2)&&M_A(sensor, 3)&&M_B(sensor, 4))
#define MATCH_ABAAB(sensor) (M_A(sensor, 0)&&M_B(sensor, 1)&&M_A(sensor, 2)&&M_A(sensor, 3)&&M_B(sensor, 4))
#define MATCH_WAAAB(sensor) (M_W(sensor, 0)&&M_A(sensor, 1)&&M_A(sensor, 2)&&M_A(sensor, 3)&&M_B(sensor, 4))
#define MATCH_BAAAB(sensor) (M_B(sensor, 0)&&M_A(sensor, 1)&&M_A(sensor, 2)&&M_A(sensor, 3)&&M_B(sensor, 4))
#define MATCH_AAAAB(sensor) (M_A(sensor, 0)&&M_A(sensor, 1)&&M_A(sensor, 2)&&M_A(sensor, 3)&&M_B(sensor, 4))
#define MATCH_WWWWA(sensor) (M_W(sensor, 0)&&M_W(sensor, 1)&&M_W(sensor, 2)&&M_W(sensor, 3)&&M_A(sensor, 4))
#define MATCH_BWWWA(sensor) (M_B(sensor, 0)&&M_W(sensor, 1)&&M_W(sensor, 2)&&M_W(sensor, 3)&&M_A(sensor, 4))
#define MATCH_AWWWA(sensor) (M_A(sensor, 0)&&M_W(sensor, 1)&&M_W(sensor, 2)&&M_W(sensor, 3)&&M_A(sensor, 4))
#define MATCH_WBWWA(sensor) (M_W(sensor, 0)&&M_B(sensor, 1)&&M_W(sensor, 2)&&M_W(sensor, 3)&&M_A(sensor, 4))
#define MATCH_BBWWA(sensor) (M_B(sensor, 0)&&M_B(sensor, 1)&&M_W(sensor, 2)&&M_W(sensor, 3)&&M_A(sensor, 4))
#define MATCH_ABWWA(sensor) (M_A(sensor, 0)&&M_B(sensor, 1)&&M_W(sensor, 2)&&M_W(sensor, 3)&&M_A(sensor, 4))
#define MATCH_WAWWA(sensor) (M_W(sensor, 0)&&M_A(sensor, 1)&&M_W(sensor, 2)&&M_W(sensor, 3)&&M_A(sensor, 4))
#define MATCH_BAWWA(sensor) (M_B(sensor, 0)&&M_A(sensor, 1)&&M_W(sensor, 2)&&M_W(sensor, 3)&&M_A(sensor, 4))
#define MATCH_AAWWA(sensor) (M_A(sensor, 0)&&M_A(sensor, 1)&&M_W(sensor, 2)&&M_W(sensor, 3)&&M_A(sensor, 4))
#define MATCH_WWBWA(sensor) (M_W(sensor, 0)&&M_W(sensor, 1)&&M_B(sensor, 2)&&M_W(sensor, 3)&&M_A(sensor, 4))
#define MATCH_BWBWA(sensor) (M_B(sensor, 0)&&M_W(sensor, 1)&&M_B(sensor, 2)&&M_W(sensor, 3)&&M_A(sensor, 4))
#define MATCH_AWBWA(sensor) (M_A(sensor, 0)&&M_W(sensor, 1)&&M_B(sensor, 2)&&M_W(sensor, 3)&&M_A(sensor, 4))
#define MATCH_WBBWA(sensor) (M_W(sensor, 0)&&M_B(sensor, 1)&&M_B(sensor, 2)&&M_W(sensor, 3)&&M_A(sensor, 4))
#define MATCH_BBBWA(sensor) (M_B(sensor, 0)&&M_B(sensor, 1)&&M_B(sensor, 2)&&M_W(sensor, 3)&&M_A(sensor, 4))
#define MATCH_ABBWA(sensor) (M_A(sensor, 0)&&M_B(sensor, 1)&&M_B(sensor, 2)&&M_W(sensor, 3)&&M_A(sensor, 4))
#define MATCH_WABWA(sensor) (M_W(sensor, 0)&&M_A(sensor, 1)&&M_B(sensor, 2)&&M_W(sensor, 3)&&M_A(sensor, 4))
#define MATCH_BABWA(sensor) (M_B(sensor, 0)&&M_A(sensor, 1)&&M_B(sensor, 2)&&M_W(sensor, 3)&&M_A(sensor, 4))
#define MATCH_AABWA(sensor) (M_A(sensor, 0)&&M_A(sensor, 1)&&M_B(sensor, 2)&&M_W(sensor, 3)&&M_A(sensor, 4))
#define MATCH_WWAWA(sensor) (M_W(sensor, 0)&&M_W(sensor, 1)&&M_A(sensor, 2)&&M_W(sensor, 3)&&M_A(sensor, 4))
#define MATCH_BWAWA(sensor) (M_B(sensor, 0)&&M_W(sensor, 1)&&M_A(sensor, 2)&&M_W(sensor, 3)&&M_A(sensor, 4))
#define MATCH_AWAWA(sensor) (M_A(sensor, 0)&&M_W(sensor, 1)&&M_A(sensor, 2)&&M_W(sensor, 3)&&M_A(sensor, 4))
#define MATCH_WBAWA(sensor) (M_W(sensor, 0)&&M_B(sensor, 1)&&M_A(sensor, 2)&&M_W(sensor, 3)&&M_A(sensor, 4))
#define MATCH_BBAWA(sensor) (M_B(sensor, 0)&&M_B(sensor, 1)&&M_A(sensor, 2)&&M_W(sensor, 3)&&M_A(sensor, 4))
#define MATCH_ABAWA(sensor) (M_A(sensor, 0)&&M_B(sensor, 1)&&M_A(sensor, 2)&&M_W(sensor, 3)&&M_A(sensor, 4))
#define MATCH_WAAWA(sensor) (M_W(sensor, 0)&&M_A(sensor, 1)&&M_A(sensor, 2)&&M_W(sensor, 3)&&M_A(sensor, 4))
#define MATCH_BAAWA(sensor) (M_B(sensor, 0)&&M_A(sensor, 1)&&M_A(sensor, 2)&&M_W(sensor, 3)&&M_A(sensor, 4))
#define MATCH_AAAWA(sensor) (M_A(sensor, 0)&&M_A(sensor, 1)&&M_A(sensor, 2)&&M_W(sensor, 3)&&M_A(sensor, 4))
#define MATCH_WWWBA(sensor) (M_W(sensor, 0)&&M_W(sensor, 1)&&M_W(sensor, 2)&&M_B(sensor, 3)&&M_A(sensor, 4))
#define MATCH_BWWBA(sensor) (M_B(sensor, 0)&&M_W(sensor, 1)&&M_W(sensor, 2)&&M_B(sensor, 3)&&M_A(sensor, 4))
#define MATCH_AWWBA(sensor) (M_A(sensor, 0)&&M_W(sensor, 1)&&M_W(sensor, 2)&&M_B(sensor, 3)&&M_A(sensor, 4))
#define MATCH_WBWBA(sensor) (M_W(sensor, 0)&&M_B(sensor, 1)&&M_W(sensor, 2)&&M_B(sensor, 3)&&M_A(sensor, 4))
#define MATCH_BBWBA(sensor) (M_B(sensor, 0)&&M_B(sensor, 1)&&M_W(sensor, 2)&&M_B(sensor, 3)&&M_A(sensor, 4))
#define MATCH_ABWBA(sensor) (M_A(sensor, 0)&&M_B(sensor, 1)&&M_W(sensor, 2)&&M_B(sensor, 3)&&M_A(sensor, 4))
#define MATCH_WAWBA(sensor) (M_W(sensor, 0)&&M_A(sensor, 1)&&M_W(sensor, 2)&&M_B(sensor, 3)&&M_A(sensor, 4))
#define MATCH_BAWBA(sensor) (M_B(sensor, 0)&&M_A(sensor, 1)&&M_W(sensor, 2)&&M_B(sensor, 3)&&M_A(sensor, 4))
#define MATCH_AAWBA(sensor) (M_A(sensor, 0)&&M_A(sensor, 1)&&M_W(sensor, 2)&&M_B(sensor, 3)&&M_A(sensor, 4))
#define MATCH_WWBBA(sensor) (M_W(sensor, 0)&&M_W(sensor, 1)&&M_B(sensor, 2)&&M_B(sensor, 3)&&M_A(sensor, 4))
#define MATCH_BWBBA(sensor) (M_B(sensor, 0)&&M_W(sensor, 1)&&M_B(sensor, 2)&&M_B(sensor, 3)&&M_A(sensor, 4))
#define MATCH_AWBBA(sensor) (M_A(sensor, 0)&&M_W(sensor, 1)&&M_B(sensor, 2)&&M_B(sensor, 3)&&M_A(sensor, 4))
#define MATCH_WBBBA(sensor) (M_W(sensor, 0)&&M_B(sensor, 1)&&M_B(sensor, 2)&&M_B(sensor, 3)&&M_A(sensor, 4))
#define MATCH_BBBBA(sensor) (M_B(sensor, 0)&&M_B(sensor, 1)&&M_B(sensor, 2)&&M_B(sensor, 3)&&M_A(sensor, 4))
#define MATCH_ABBBA(sensor) (M_A(sensor, 0)&&M_B(sensor, 1)&&M_B(sensor, 2)&&M_B(sensor, 3)&&M_A(sensor, 4))
#define MATCH_WABBA(sensor) (M_W(sensor, 0)&&M_A(sensor, 1)&&M_B(sensor, 2)&&M_B(sensor, 3)&&M_A(sensor, 4))
#define MATCH_BABBA(sensor) (M_B(sensor, 0)&&M_A(sensor, 1)&&M_B(sensor, 2)&&M_B(sensor, 3)&&M_A(sensor, 4))
#define MATCH_AABBA(sensor) (M_A(sensor, 0)&&M_A(sensor, 1)&&M_B(sensor, 2)&&M_B(sensor, 3)&&M_A(sensor, 4))
#define MATCH_WWABA(sensor) (M_W(sensor, 0)&&M_W(sensor, 1)&&M_A(sensor, 2)&&M_B(sensor, 3)&&M_A(sensor, 4))
#define MATCH_BWABA(sensor) (M_B(sensor, 0)&&M_W(sensor, 1)&&M_A(sensor, 2)&&M_B(sensor, 3)&&M_A(sensor, 4))
#define MATCH_AWABA(sensor) (M_A(sensor, 0)&&M_W(sensor, 1)&&M_A(sensor, 2)&&M_B(sensor, 3)&&M_A(sensor, 4))
#define MATCH_WBABA(sensor) (M_W(sensor, 0)&&M_B(sensor, 1)&&M_A(sensor, 2)&&M_B(sensor, 3)&&M_A(sensor, 4))
#define MATCH_BBABA(sensor) (M_B(sensor, 0)&&M_B(sensor, 1)&&M_A(sensor, 2)&&M_B(sensor, 3)&&M_A(sensor, 4))
#define MATCH_ABABA(sensor) (M_A(sensor, 0)&&M_B(sensor, 1)&&M_A(sensor, 2)&&M_B(sensor, 3)&&M_A(sensor, 4))
#define MATCH_WAABA(sensor) (M_W(sensor, 0)&&M_A(sensor, 1)&&M_A(sensor, 2)&&M_B(sensor, 3)&&M_A(sensor, 4))
#define MATCH_BAABA(sensor) (M_B(sensor, 0)&&M_A(sensor, 1)&&M_A(sensor, 2)&&M_B(sensor, 3)&&M_A(sensor, 4))
#define MATCH_AAABA(sensor) (M_A(sensor, 0)&&M_A(sensor, 1)&&M_A(sensor, 2)&&M_B(sensor, 3)&&M_A(sensor, 4))
#define MATCH_WWWAA(sensor) (M_W(sensor, 0)&&M_W(sensor, 1)&&M_W(sensor, 2)&&M_A(sensor, 3)&&M_A(sensor, 4))
#define MATCH_BWWAA(sensor) (M_B(sensor, 0)&&M_W(sensor, 1)&&M_W(sensor, 2)&&M_A(sensor, 3)&&M_A(sensor, 4))
#define MATCH_AWWAA(sensor) (M_A(sensor, 0)&&M_W(sensor, 1)&&M_W(sensor, 2)&&M_A(sensor, 3)&&M_A(sensor, 4))
#define MATCH_WBWAA(sensor) (M_W(sensor, 0)&&M_B(sensor, 1)&&M_W(sensor, 2)&&M_A(sensor, 3)&&M_A(sensor, 4))
#define MATCH_BBWAA(sensor) (M_B(sensor, 0)&&M_B(sensor, 1)&&M_W(sensor, 2)&&M_A(sensor, 3)&&M_A(sensor, 4))
#define MATCH_ABWAA(sensor) (M_A(sensor, 0)&&M_B(sensor, 1)&&M_W(sensor, 2)&&M_A(sensor, 3)&&M_A(sensor, 4))
#define MATCH_WAWAA(sensor) (M_W(sensor, 0)&&M_A(sensor, 1)&&M_W(sensor, 2)&&M_A(sensor, 3)&&M_A(sensor, 4))
#define MATCH_BAWAA(sensor) (M_B(sensor, 0)&&M_A(sensor, 1)&&M_W(sensor, 2)&&M_A(sensor, 3)&&M_A(sensor, 4))
#define MATCH_AAWAA(sensor) (M_A(sensor, 0)&&M_A(sensor, 1)&&M_W(sensor, 2)&&M_A(sensor, 3)&&M_A(sensor, 4))
#define MATCH_WWBAA(sensor) (M_W(sensor, 0)&&M_W(sensor, 1)&&M_B(sensor, 2)&&M_A(sensor, 3)&&M_A(sensor, 4))
#define MATCH_BWBAA(sensor) (M_B(sensor, 0)&&M_W(sensor, 1)&&M_B(sensor, 2)&&M_A(sensor, 3)&&M_A(sensor, 4))
#define MATCH_AWBAA(sensor) (M_A(sensor, 0)&&M_W(sensor, 1)&&M_B(sensor, 2)&&M_A(sensor, 3)&&M_A(sensor, 4))
#define MATCH_WBBAA(sensor) (M_W(sensor, 0)&&M_B(sensor, 1)&&M_B(sensor, 2)&&M_A(sensor, 3)&&M_A(sensor, 4))
#define MATCH_BBBAA(sensor) (M_B(sensor, 0)&&M_B(sensor, 1)&&M_B(sensor, 2)&&M_A(sensor, 3)&&M_A(sensor, 4))
#define MATCH_ABBAA(sensor) (M_A(sensor, 0)&&M_B(sensor, 1)&&M_B(sensor, 2)&&M_A(sensor, 3)&&M_A(sensor, 4))
#define MATCH_WABAA(sensor) (M_W(sensor, 0)&&M_A(sensor, 1)&&M_B(sensor, 2)&&M_A(sensor, 3)&&M_A(sensor, 4))
#define MATCH_BABAA(sensor) (M_B(sensor, 0)&&M_A(sensor, 1)&&M_B(sensor, 2)&&M_A(sensor, 3)&&M_A(sensor, 4))
#define MATCH_AABAA(sensor) (M_A(sensor, 0)&&M_A(sensor, 1)&&M_B(sensor, 2)&&M_A(sensor, 3)&&M_A(sensor, 4))
#define MATCH_WWAAA(sensor) (M_W(sensor, 0)&&M_W(sensor, 1)&&M_A(sensor, 2)&&M_A(sensor, 3)&&M_A(sensor, 4))
#define MATCH_BWAAA(sensor) (M_B(sensor, 0)&&M_W(sensor, 1)&&M_A(sensor, 2)&&M_A(sensor, 3)&&M_A(sensor, 4))
#define MATCH_AWAAA(sensor) (M_A(sensor, 0)&&M_W(sensor, 1)&&M_A(sensor, 2)&&M_A(sensor, 3)&&M_A(sensor, 4))
#define MATCH_WBAAA(sensor) (M_W(sensor, 0)&&M_B(sensor, 1)&&M_A(sensor, 2)&&M_A(sensor, 3)&&M_A(sensor, 4))
#define MATCH_BBAAA(sensor) (M_B(sensor, 0)&&M_B(sensor, 1)&&M_A(sensor, 2)&&M_A(sensor, 3)&&M_A(sensor, 4))
#define MATCH_ABAAA(sensor) (M_A(sensor, 0)&&M_B(sensor, 1)&&M_A(sensor, 2)&&M_A(sensor, 3)&&M_A(sensor, 4))
#define MATCH_WAAAA(sensor) (M_W(sensor, 0)&&M_A(sensor, 1)&&M_A(sensor, 2)&&M_A(sensor, 3)&&M_A(sensor, 4))
#define MATCH_BAAAA(sensor) (M_B(sensor, 0)&&M_A(sensor, 1)&&M_A(sensor, 2)&&M_A(sensor, 3)&&M_A(sensor, 4))
#define MATCH_AAAAA(sensor) (M_A(sensor, 0)&&M_A(sensor, 1)&&M_A(sensor, 2)&&M_A(sensor, 3)&&M_A(sensor, 4))

#define MATCH(sensor, pattern) (MATCH_ ## pattern (sensor))
